services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  nginx:
    image: 'nginx:1.23.3-alpine'
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    environment:
      - 'PMA_HOST=mysql'
      - 'UPLOAD_LIMIT=102400K'

  mailpit:
    image: 'axllent/mailpit:v1.7'

  swagger-ui:
    platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.10.5
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
  
  baikal:
    image: ckulka/baikal:0.10.1-apache
    volumes:
      - ./docker/baikal:/var/www/html
      - ./docker/baikal/config:/var/www/baikal/config
      - ./docker/baikal/data:/var/www/baikal/Specific
  
  openldap:
    image: osixia/openldap:1.5.0
    hostname: openldap
    volumes:
      - ./docker/openldap/certificates:/container/service/slapd/assets/certs
      - ./docker/openldap/slapd/database:/var/lib/ldap
      - ./docker/openldap/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=example,dc=org"
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user
      - LDAP_READONLY_USER_PASSWORD=password

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap

